import { PrismaClient, RoleName, FieldType, LeadType, LeadStatus, ProductStatus } from "@prisma/client";
import { scryptSync } from "node:crypto";
const db=new PrismaClient();const hash=(p:string)=>scryptSync(p,"propulse-demo-salt",32).toString("hex");
async function main(){
const permissions=["admin:dashboard","admin:users","admin:leads","admin:pricing","admin:memberships","admin:investments","admin:booster","admin:wallet","admin:payments","admin:coupons","admin:settings","admin:audit"];
for(const key of permissions)await db.permission.upsert({where:{key},update:{},create:{key}});for(const name of Object.values(RoleName))await db.role.upsert({where:{name},update:{},create:{name}});
const adminRole=await db.role.findUniqueOrThrow({where:{name:RoleName.SUPER_ADMIN}});for(const p of await db.permission.findMany())await db.rolePermission.upsert({where:{roleId_permissionId:{roleId:adminRole.id,permissionId:p.id}},update:{},create:{roleId:adminRole.id,permissionId:p.id}});
const admin=await db.user.upsert({where:{email:"admin@propulse.local"},update:{},create:{email:"admin@propulse.local",mobile:"9999999999",name:"Propulse Super Admin",passwordHash:hash("ChangeMeImmediately!123"),status:"ACTIVE",profile:{create:{companyName:"Propulse Business",city:"Hyderabad",state:"Telangana",country:"India"}}}});
await db.userRole.upsert({where:{userId_roleId:{userId:admin.id,roleId:adminRole.id}},update:{},create:{userId:admin.id,roleId:adminRole.id}});
const industries=[{name:"Interior Design",slug:"interior-design",fields:[["propertyType","Property Type",FieldType.SELECT],["area","Area",FieldType.NUMBER],["budget","Budget",FieldType.CURRENCY],["requirement","Requirement",FieldType.TEXT]]},{name:"Real Estate",slug:"real-estate",fields:[["propertyType","Property Type",FieldType.SELECT],["budget","Budget",FieldType.CURRENCY],["requirement","Requirement",FieldType.TEXT],["intent","Buying / Renting",FieldType.SELECT]]},{name:"Education",slug:"education",fields:[["course","Course",FieldType.TEXT],["studentRequirement","Student Requirement",FieldType.TEXT],["budget","Budget",FieldType.CURRENCY]]},{name:"Construction",slug:"construction",fields:[["projectType","Project Type",FieldType.TEXT],["projectSize","Project Size",FieldType.NUMBER],["budget","Budget",FieldType.CURRENCY]]}];
for(const item of industries){const ind=await db.industry.upsert({where:{slug:item.slug},update:{},create:{name:item.name,slug:item.slug}});for(const [key,label,type] of item.fields)await db.leadField.upsert({where:{industryId_categoryId_key:{industryId:ind.id,categoryId:null,key:key as string}},update:{},create:{industryId:ind.id,key:key as string,label:label as string,type:type as FieldType,searchable:true,filterable:true}})}
await db.membershipPlan.upsert({where:{code:"PRO"},update:{},create:{code:"PRO",name:"Pro",priceMinor:99900n,durationDays:30,benefitsJson:["Pro lead pricing","Exclusive leads","Investment eligibility","Booster access"]}});
const realEstate=await db.industry.findUniqueOrThrow({where:{slug:"real-estate"}});await db.investmentRule.upsert({where:{id:"seed-real-estate-rule"},update:{},create:{id:"seed-real-estate-rule",industryId:realEstate.id,minimumMinor:100000n,maximumMinor:1000000n,capacityMinor:5000000n}});
await db.boosterProduct.upsert({where:{code:"BOOSTER_STARTER"},update:{},create:{code:"BOOSTER_STARTER",name:"Booster Starter",description:"Digital marketing package for professionals.",priceMinor:499900n,durationDays:30,status:ProductStatus.ACTIVE,featuresJson:["Campaign setup","Lead-generation strategy","Monthly performance review"]}});
const ind=await db.industry.findUniqueOrThrow({where:{slug:"interior-design"}});const cat=await db.category.upsert({where:{industryId_slug:{industryId:ind.id,slug:"residential-interiors"}},update:{},create:{industryId:ind.id,name:"Residential Interiors",slug:"residential-interiors"}});const pf=await db.leadField.findFirstOrThrow({where:{industryId:ind.id,key:"propertyType"}});const bf=await db.leadField.findFirstOrThrow({where:{industryId:ind.id,key:"budget"}});
await db.lead.create({data:{industryId:ind.id,categoryId:cat.id,title:"Residential interior project",service:"Complete home interiors",city:"Hyderabad",state:"Telangana",requirementSummary:"3BHK homeowner seeking turnkey interior design.",leadType:LeadType.SHARED,status:LeadStatus.ACTIVE,normalPriceMinor:249900n,proPriceMinor:199900n,maxBuyers:3,contactName:"Demo Prospect",contactEmail:"contact@example.invalid",contactMobile:"9000000000",fields:{create:[{fieldId:pf.id,value:"3BHK"},{fieldId:bf.id,value:"800000"}]}}});console.log("Seed complete. Admin: admin@propulse.local / ChangeMeImmediately!123")}
main().finally(()=>db.$disconnect());
